build:
  date: '@build.date@'
jwt:
  expiration: 1296000000
  secret: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa
logging:
  file:
    name: ./cow-economy-web.log
  level:
    com:
      samsung:
        security: DEBUG
    org:
      apache:
        tiles: INFO
      springframework:
        web: DEBUG
        #        boot: DEBUG
        security: DEBUG
    root: INFO
management:
  health:
    db:
      enabled: true
    default:
      enabled: true
    diskspace:
      enabled: true
  servlet:
    context-path: /manage
server:
  address: localhost
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
  port: 5000
  servlet:
    contextPath: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spa:
  default-file: /dist/index.html
spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      password: ssafy
      username: root
    url: jdbc:mysql://localhost:3306/ssafy_cow_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
  devtools:
    livereload:
      enabled: true
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
      static-locations: classpath:/dist/

springfox:
  documentation:
    swagger:
      use-model-v3: false



